name: Access Secrets

on:
  push:
    branches:
      - main

jobs:
  access-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Print Secret
        run: echo "Secret is accessible"
        env:
          HF_KEY: ${{ secrets.HF_KEY }}
